CREATE DATABASE BCP
GO

USE BCP
GO

CREATE TABLE MONEDA (
   ID int identity,
   COD_MONEDA CHAR(3),
   TXT_SIMBOLO CHAR(5),
)

GO

INSERT INTO MONEDA (COD_MONEDA, TXT_SIMBOLO) VALUES ('PEN', 'S/');
INSERT INTO MONEDA (COD_MONEDA, TXT_SIMBOLO) VALUES ('USD', '$');
INSERT INTO MONEDA (COD_MONEDA, TXT_SIMBOLO) VALUES ('EUR', '€');

CREATE TABLE TIPOCAMBIO (
   ID INT IDENTITY,
   ID_MONEDA_ORIGEN INT,
   ID_MONEDA_DESTINO INT,
   IMP_COMPRA DECIMAL(3,2),
   IMP_VENTA DECIMAL(3,2)
)

GO

INSERT INTO TIPOCAMBIO (ID_MONEDA_ORIGEN, ID_MONEDA_DESTINO, IMP_COMPRA, IMP_VENTA) VALUES (1, 2, 3.726, 3.788 );
GO
INSERT INTO TIPOCAMBIO (ID_MONEDA_ORIGEN, ID_MONEDA_DESTINO, IMP_COMPRA, IMP_VENTA) VALUES (1, 3 , 4.14, 4.38 );
GO

CREATE PROCEDURE SPGETMONEDAS 
AS	
  BEGIN
  SELECT ID AS IDMONEDA,
         COD_MONEDA AS COD_MONEDA,
	     TXT_SIMBOLO AS TXT_SIMBOLO  FROM MONEDA
  END
		



